# API Keys and Database Configuration
[openai]
api_key = "your-openai-api-key-here"

[mongodb]
connection_string = "your-mongodb-connection-string-here"
database_name = "chat_app_mvp"

# Example connection strings:
# For MongoDB Atlas: "mongodb+srv://username:password@cluster.mongodb.net/"
# For local MongoDB: "mongodb://localhost:27017/"